name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.lifeswap.LifeSwap
version: ${version}
api-version: 1.13

commands:
  reset:
    description: Command for resetting all players
    permission: lifeswap.reset
  swap:
    description: Swaps players
    permission: lifeswap.swap

permissions:
  lifeswap.reset:
    description: Allows you to use /reset
  lifeswap.swap:
    description: Allows you to use /swap
