name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13

commands:
  lifeswapreload:
    description: Command for reloading the plugin
    aliases:
      - swapreload
    permission: lifeswap.reload
  lifeswapstart:
    description: Starts a swap game
    aliases:
      - swap
      - swapstart
      - startswap
      - startlifeswap
    permission: lifeswap.start
  lifeswapstop:
    description: "Stop (a) swap game(s)"
    aliases:
      - swapstop
      - stopswap
      - stoplifeswap
    permission: lifeswap.stop

permissions:
  lifeswap.reload:
    description: Allows you to use /lifeswapreload
  lifeswap.start:
    description: Allows you to use /lifeswapstart
  lifeswap.stop:
    description: Allows you to use /lifeswapstop
