name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.lifeswap.LifeSwap
version: ${version}
api-version: 1.13

commands:
  lifeswapreload:
    description: Command for reloading the plugin
    aliases:
      - lifereload
      - swapreload
      - lsreload
    permission: lifeswap.reload
  reset:
    description: Command for resetting all players
    permission: lifeswap.reset
  swap:
    description: Swaps players
    permission: lifeswap.swap

permissions:
  lifeswap.reload:
    description: Allows you to use /lifeswapreload
  lifeswap.reset:
    description: Allows you to use /reset
  lifeswap.swap:
    description: Allows you to use /swap
