name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: KX9guorr
      curseforge: 896916
    secrets: inherit
    permissions:
      contents: write
